#!/bin/bash
#
# tomcat   Start the tomcat server.
#

NAME="Tomcat 7"
TOMCAT_HOME=/opt/tomcat7
CATALINA_HOME=/opt/tomcat7
JAVA_HOME=/opt/jre7
TOMCAT_USER=tomcat

export TOMCAT_HOME CATALINA_HOME JAVA_HOME TOMCAT_USER
cd $TOMCAT_HOME/logs
case "$1" in
  start)
    echo -ne "Starting $NAME. "
    iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 8080
	/bin/su $TOMCAT_USER $TOMCAT_HOME/bin/startup.sh
    ;;

  stop)
    echo -ne "Stopping $NAME. "
	iptables -D PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 8080
    /bin/su $TOMCAT_USER $TOMCAT_HOME/bin/shutdown.sh
    ;;

  restart)
    echo -ne "Restarting $NAME. "
	/bin/su $TOMCAT_USER $TOMCAT_HOME/bin/shutdown.sh
	/bin/su $TOMCAT_USER $TOMCAT_HOME/bin/startup.sh
	;;
	
  *)
    echo "Usage: /etc/init.d/tomcat {start|stop|restart}"
    exit 1
    ;;
esac

exit 0